export const PopupActionTypes =
{
    TOGGLE_POPUP_HIDDEN_EMOTES: 'TOGGLE_POPUP_HIDDEN_EMOTES',
    TOGGLE_POPUP_HIDDEN_CREATE: 'TOGGLE_POPUP_HIDDEN_CREATE',
    TOGGLE_POPUP_HIDDEN_UPDATE: 'TOGGLE_POPUP_HIDDEN_UPDATE',
    TOGGLE_POPUP_HIDDEN_CONFIRM: 'TOGGLE_POPUP_HIDDEN_CONFIRM'
};
